services:
  # Cognee MCP Server - Model Context Protocol server for IDE integration
  cognee-mcp:
    container_name: cognee-mcp
    profiles:
      - mcp
    networks:
      - cognee-network
    build:
      context: .
      dockerfile: cognee-mcp/Dockerfile
    volumes:
      - .env:/app/.env
    environment:
      - DEBUG=false # Change to true if debugging
      - ENVIRONMENT=local
      - LOG_LEVEL=INFO
      - TRANSPORT_MODE=sse
      # Database configuration - should match the main cognee service
      - DB_PROVIDER=${DB_PROVIDER:-postgres}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-cognee_db}
      - DB_USERNAME=${DB_USERNAME:-cognee}
      - DB_PASSWORD=${DB_PASSWORD:-cognee}
      # MCP specific configuration
      - MCP_LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000" # MCP port
      - "5678:5678" # MCP debugger port
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4GB

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    profiles:
      - qdrant
    ports:
      - "6333:6333" # REST API port
      - "6334:6334" # gRPC port
    environment:
      - QDRANT__SERVICE__API_KEY=cognee
    networks:
      - cognee-network
    volumes:
      - qdrant_storage:/qdrant/storage

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    profiles:
      - neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    networks:
      - cognee-network
    volumes:
      - neo4j_data:/var/lib/neo4j/data

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    profiles:
      - postgres
    environment:
      POSTGRES_USER: cognee
      POSTGRES_PASSWORD: cognee
      POSTGRES_DB: cognee_db
    ports:
      - 5432:5432
    networks:
      - cognee-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  cognee-network:
    name: cognee-network

volumes:
  qdrant_storage:
  postgres_data:
  neo4j_data:
  


